version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - revive
    - staticcheck

formatters:
  enable:
    - gofmt
    - gci

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - say_reasons
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/eugenenazirov/re-partners)
    skip-generated: true
    skip-vendor: true
